// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRemoteServer(arg1:main.OllamaServerConfig):Promise<void>;

export function ChatMessage(arg1:string,arg2:Array<main.Message>):Promise<string>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteRemoteServer(arg1:string):Promise<void>;

export function GetActiveServer():Promise<main.OllamaServerConfig>;

export function GetModelFamilies():Promise<Array<string>>;

export function GetModelParams(arg1:string):Promise<Record<string, any>>;

export function GetModelSettings(arg1:string):Promise<Record<string, any>>;

export function GetModelStatus(arg1:string):Promise<Record<string, any>>;

export function GetModelTags():Promise<Array<string>>;

export function GetOllamaServerConfig():Promise<string>;

export function GetRemoteServers():Promise<Array<main.OllamaServerConfig>>;

export function ListModels():Promise<Array<main.Model>>;

export function ListModelsByServer(arg1:string):Promise<Array<main.Model>>;

export function ListRunningModels():Promise<Array<Record<string, any>>>;

export function LoadModel(arg1:string):Promise<void>;

export function PullModel(arg1:string):Promise<void>;

export function RunModel(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveModelSettings(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveOllamaServerConfig(arg1:string):Promise<void>;

export function SaveRemoteServers(arg1:Array<main.OllamaServerConfig>):Promise<void>;

export function SearchModels(arg1:Record<string, any>):Promise<Array<main.Model>>;

export function SetActiveServer(arg1:string):Promise<void>;

export function SetModelParams(arg1:string,arg2:Record<string, any>):Promise<void>;

export function StopModel(arg1:string):Promise<void>;

export function TestModel(arg1:string):Promise<string>;

export function TestOllamaServer(arg1:string):Promise<void>;

export function UnloadModel(arg1:string):Promise<void>;

export function UpdateRemoteServer(arg1:main.OllamaServerConfig):Promise<void>;
