// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRemoteServer(arg1:main.OllamaServerConfig):Promise<void>;

export function ChatMessage(arg1:string,arg2:Array<main.Message>,arg3:any):Promise<string>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteRemoteServer(arg1:string):Promise<void>;

export function DownloadModel(arg1:string,arg2:string):Promise<void>;

export function GetActiveServer():Promise<main.OllamaServerConfig>;

export function GetLocalServerTestStatus():Promise<string>;

export function GetModelParams(arg1:string):Promise<Record<string, any>>;

export function GetOllamaServerConfig():Promise<string>;

export function GetRemoteServers():Promise<Array<main.OllamaServerConfig>>;

export function KVDelete(arg1:string):Promise<void>;

export function KVGet(arg1:string):Promise<string>;

export function KVList(arg1:string):Promise<string>;

export function KVSet(arg1:string,arg2:string):Promise<void>;

export function ListModelsByServer(arg1:string):Promise<Array<main.Model>>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function RunModel(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveLocalServerTestStatus(arg1:string):Promise<void>;

export function SaveOllamaServerConfig(arg1:string):Promise<void>;

export function SearchOnlineModels(arg1:string):Promise<Array<any>>;

export function SetActiveServer(arg1:string):Promise<void>;

export function SetModelParams(arg1:string,arg2:Record<string, any>):Promise<void>;

export function StopModel(arg1:string):Promise<void>;

export function TestModel(arg1:string,arg2:string):Promise<string>;

export function TestOllamaConnection():Promise<boolean>;

export function TestOllamaServer(arg1:string):Promise<string>;

export function UpdateRemoteServer(arg1:main.OllamaServerConfig):Promise<void>;
