// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ChatMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatMessage'](arg1, arg2, arg3);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeletePrompt(arg1) {
  return window['go']['main']['App']['DeletePrompt'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
}

export function GeneratePromptStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePromptStream'](arg1, arg2, arg3);
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetModelParams(arg1) {
  return window['go']['main']['App']['GetModelParams'](arg1);
}

export function GetOllamaServers() {
  return window['go']['main']['App']['GetOllamaServers']();
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListModelsByServer(arg1) {
  return window['go']['main']['App']['ListModelsByServer'](arg1);
}

export function ListPrompts() {
  return window['go']['main']['App']['ListPrompts']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OptimizePrompt(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OptimizePrompt'](arg1, arg2, arg3, arg4);
}

export function RunModel(arg1, arg2) {
  return window['go']['main']['App']['RunModel'](arg1, arg2);
}

export function SaveConversation(arg1) {
  return window['go']['main']['App']['SaveConversation'](arg1);
}

export function SavePrompt(arg1) {
  return window['go']['main']['App']['SavePrompt'](arg1);
}

export function SearchOnlineModels(arg1) {
  return window['go']['main']['App']['SearchOnlineModels'](arg1);
}

export function SendHttpRequest(arg1) {
  return window['go']['main']['App']['SendHttpRequest'](arg1);
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetModelParams(arg1, arg2) {
  return window['go']['main']['App']['SetModelParams'](arg1, arg2);
}

export function StopModel(arg1) {
  return window['go']['main']['App']['StopModel'](arg1);
}

export function TestModel(arg1, arg2) {
  return window['go']['main']['App']['TestModel'](arg1, arg2);
}

export function TestOllamaServer(arg1) {
  return window['go']['main']['App']['TestOllamaServer'](arg1);
}

export function UpdateServer(arg1) {
  return window['go']['main']['App']['UpdateServer'](arg1);
}

export function UpdateServerTestStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateServerTestStatus'](arg1, arg2);
}
