// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServer(arg1:main.OllamaServerConfig):Promise<void>;

export function ChatMessage(arg1:string,arg2:Array<main.Message>,arg3:boolean):Promise<string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeletePrompt(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DownloadModel(arg1:string,arg2:string):Promise<void>;

export function GeneratePromptStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveServer():Promise<main.OllamaServerConfig>;

export function GetConversation(arg1:string):Promise<main.Conversation>;

export function GetModelParams(arg1:string):Promise<Record<string, any>>;

export function GetPrompt(arg1:string):Promise<main.Prompt>;

export function GetServers():Promise<Array<main.OllamaServerConfig>>;

export function KVDelete(arg1:string):Promise<void>;

export function KVGet(arg1:string):Promise<string>;

export function KVList(arg1:string):Promise<string>;

export function KVSet(arg1:string,arg2:string):Promise<void>;

export function ListConversations():Promise<Array<main.Conversation>>;

export function ListModelsByServer(arg1:string):Promise<Array<main.Model>>;

export function ListPrompts():Promise<Array<main.Prompt>>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function OptimizePrompt(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RunModel(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SaveConversation(arg1:main.Conversation):Promise<main.Conversation>;

export function SavePrompt(arg1:main.Prompt):Promise<void>;

export function SearchOnlineModels(arg1:string):Promise<Array<any>>;

export function SetActiveServer(arg1:string):Promise<void>;

export function SetModelParams(arg1:string,arg2:Record<string, any>):Promise<void>;

export function StopModel(arg1:string):Promise<void>;

export function TestModel(arg1:string,arg2:string):Promise<string>;

export function TestOllamaConnection():Promise<boolean>;

export function TestOllamaServer(arg1:string):Promise<string>;

export function UpdateServer(arg1:main.OllamaServerConfig):Promise<void>;

export function UpdateServerTestStatus(arg1:string,arg2:string):Promise<void>;
