// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRemoteServer(arg1) {
  return window['go']['main']['App']['AddRemoteServer'](arg1);
}

export function ChatMessage(arg1, arg2) {
  return window['go']['main']['App']['ChatMessage'](arg1, arg2);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteRemoteServer(arg1) {
  return window['go']['main']['App']['DeleteRemoteServer'](arg1);
}

export function DownloadModel(arg1, arg2) {
  return window['go']['main']['App']['DownloadModel'](arg1, arg2);
}

export function GetActiveServer() {
  return window['go']['main']['App']['GetActiveServer']();
}

export function GetLocalServerTestStatus() {
  return window['go']['main']['App']['GetLocalServerTestStatus']();
}

export function GetModelParams(arg1) {
  return window['go']['main']['App']['GetModelParams'](arg1);
}

export function GetOllamaServerConfig() {
  return window['go']['main']['App']['GetOllamaServerConfig']();
}

export function GetRemoteServers() {
  return window['go']['main']['App']['GetRemoteServers']();
}

export function ListModelsByServer(arg1) {
  return window['go']['main']['App']['ListModelsByServer'](arg1);
}

export function RunModel(arg1, arg2) {
  return window['go']['main']['App']['RunModel'](arg1, arg2);
}

export function SaveLocalServerTestStatus(arg1) {
  return window['go']['main']['App']['SaveLocalServerTestStatus'](arg1);
}

export function SaveOllamaServerConfig(arg1) {
  return window['go']['main']['App']['SaveOllamaServerConfig'](arg1);
}

export function SearchModels(arg1) {
  return window['go']['main']['App']['SearchModels'](arg1);
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetModelParams(arg1, arg2) {
  return window['go']['main']['App']['SetModelParams'](arg1, arg2);
}

export function StopModel(arg1) {
  return window['go']['main']['App']['StopModel'](arg1);
}

export function TestModel(arg1, arg2) {
  return window['go']['main']['App']['TestModel'](arg1, arg2);
}

export function TestOllamaServer(arg1) {
  return window['go']['main']['App']['TestOllamaServer'](arg1);
}

export function UpdateRemoteServer(arg1) {
  return window['go']['main']['App']['UpdateRemoteServer'](arg1);
}
